/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsCsvParserOptions {
  escape?: string
  quote?: string
  separator?: string
  newline?: string
  raw?: boolean
  strict?: boolean
  maxRowBytes?: number
  headers?: Array<string>
  skipComments?: unknown
  skipLines?: number
}
export interface ParsedRow {
  values: Array<string>
}
export declare class CsvParser {
  constructor(options?: JsCsvParserOptions | undefined | null)
  push(chunk: Buffer): Array<ParsedRow>
  finish(): Array<ParsedRow>
  getHeaders(): Array<string> | null
  transform(chunk: Buffer): Array<object>
  flush(): Array<object>
}
